spring:
    application:
        name: postgres-service
    datasource:
        url: jdbc:postgresql://localhost:5432/records
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: true